### Data Sci

### INSTALLING NUMPY LIBRARY

In [1]:
#!pip install numpy

You should consider upgrading via the 'c:\users\admin\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


## calling numpy

In [1]:
import numpy as np

In [4]:
#to show versionof  numpy: useing inbult method __version__
np.__version__

'1.19.2'

In [5]:
#NumPy Array:
#there are 3 type of array
'''
1.Single dimention  array(1D array means vector)
2.Two dimention  array(2D array means Matrix)
3.Three dimention  array(1D array means Tensor)
'''

'\n1.Single dimention  array(1D array means vector)\n2.Two dimention  array(2D array means Matrix)\n3.Three dimention  array(1D array means Tensor)\n'

In [6]:
#Single dimention array(1D array): many row/records but one coloum
#Creat 1D numpy arrayb with the helpof list
x=[56,89,45,65,89.50,30] #creating list
print("list: ",x)

list:  [56, 89, 45, 65, 89.5, 30]


In [7]:
type(x)

list

In [8]:
#converting to  1d NumPy array
a=np.array(x) #here "a" is user defined numpy array
print(a)

[56.  89.  45.  65.  89.5 30. ]


In [11]:
y=[56,89,"Rakhi",65,89.50,30]# if there is a sring value in list
z=np.array(y)# converts every value as string because array consist of similiar type of data
print(z)#it takes biger type which can contain all type of data

['56' '89' 'Rakhi' '65' '89.5' '30']


In [13]:
b=np.array(x,int)
print(b)

[56 89 45 65 89 30]


In [18]:
print(type(x))
print(type(a))
print(type(b))
print(type(z))#nd array means No. of dimentions array

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
#checking which type of dimention in NumPy array of above: then use inbult attribute ndim
print(a.ndim)#objectname.ndim (syntax)
print(b.ndim)

1
1


In [24]:
# to show how many rows and how many coloumn 
#and it shows No.of ros and coloumn in tuple
a.shape

(6,)

In [26]:
#to  show datatype of array a: use inbuilt attribute dtype
print(a.dtype)#1 byte =8bit
print(b.dtype)#4byte =8*4 =32bit
print(z.dtype)#8byte =8*8 =64bit

float64
int32
<U11


In [27]:
print(a.itemsize)#to show how many bytes consumed by each value
print(b.itemsize)
print(z.itemsize)

8
4
44


In [28]:
print(a.size)#to show how many No. of element in numpy array
print(b.size)
print(z.size)

6
6
6


In [30]:
#memory consumed by 1D array 'a' use inbult attribute nbytes
print(a.nbytes)
print(b.nbytes)
print(z.nbytes)
#formula: No. of element in numpy array 'a'*memory consumed by each element

48
24
264


In [1]:
#Attributes od NUmpy Array
#1. ndim
#2. dtype
#3. nbytes
#4. itemsize
#5. size
#6. shape

### Access data from numpy arry
1. numpy array  is ordered
2. so, there are data access from numpy by 2 types similar to the list datatype
-- through indexing --
-- through slicing --

In [4]:
q=[10,20,40,50,70,90,72]
r=np.array(q)
print(r)

[10 20 40 50 70 90 72]


## by indexing

In [6]:
print(r[2])
print(r[-3])
print(r[6])

40
70
72


In [12]:
print(r[7])

IndexError: index 7 is out of bounds for axis 0 with size 7

In [21]:
#access data from multiple index in  single numpy array
#access data at 2nd index,5th index, 6th index
i=[2,5,6]
r[i]


array([40, 90, 72])

In [20]:
#direct method
r[[2,5,6]]

array([40, 90, 72])

## By slicing 

In [31]:
r[2:6]
#from 2nd index to 5th index

array([40, 50, 70, 90])

In [46]:
#negetive slicing/ reverse slicing
r[::-1]

array([72, 90, 70, 50, 40, 20, 10])

In [30]:
#first five
r[:5:]

array([10, 20, 40, 50, 70])

In [34]:
#last three
r[-3::1]

array([70, 90, 72])

In [35]:
r[-3:-1]

array([70, 90])

In [40]:
r[-3:1]

array([], dtype=int32)

In [44]:
#access even index data
r[::2]

array([10, 40, 70, 72])

In [45]:
#access odd index data
r[1::2]

array([20, 50, 90])

## mathmetical operation on Numpy array

In [49]:
#finding squar root of each element of NumPy array
print(r)
np.sqrt(r)

[10 20 40 50 70 90 72]


array([3.16227766, 4.47213595, 6.32455532, 7.07106781, 8.36660027,
       9.48683298, 8.48528137])

In [50]:
#finding sum of all data in array
print(r)
np.sum(r)

[10 20 40 50 70 90 72]


352

In [52]:
#to find avg of each element in array mean()
#averag(mean)= sum of each elemet/no of element
np.mean(r)

50.285714285714285

In [53]:
#to find max value and min value in the data
np.max(r)

90

In [54]:
np.min(r)

10

## deleting element from array

In [56]:
#use inbult function delete() which is defined in NumPy library
np.delete(r,-1)#syntex np.delete(array name,index)

array([10, 20, 40, 50, 70, 90])

In [59]:
#to delete element from multiple index
#delete 1,2,5
np.delete(r,[1,2,5])#temperory delete

array([10, 50, 70, 72])

In [63]:
#for permanent delete
r=np.delete(r,[1,3,5])

IndexError: index 5 is out of bounds for axis 0 with size 4

In [65]:
r# profe of permanent delete

array([10, 40, 70, 72])

# append()

In [67]:
#to add new element at the end of the numpy array
#to add single element in existing numpy array
np.append(r,89)# temperory addition of element

array([10, 40, 70, 72, 89])

In [68]:
r#prove

array([10, 40, 70, 72])

In [70]:
r=np.append(r,89)#permanent addition of element

In [74]:
r#prove

array([10, 40, 70, 72, 89])

In [75]:
#to add multiple element at the end of  numpy array but temporary
np.append(r,[100,300,400])

array([ 10,  40,  70,  72,  89, 100, 300, 400])

In [77]:
#inserting new element at particular index
np.insert(r,2,500)#temperory

array([ 10,  40, 500,  70,  72,  89])

In [79]:
#inserting new element at particular index
r=np.insert(r,2,500)#permanent
print(r)

[ 10  40 500 500  70  72  89]


In [81]:
### to access whoes values is  even no
index=np.where(r%2==0)
#index of specified condition
print(index)
print('value : ',r[index])

(array([0, 1, 2, 3, 4, 5], dtype=int64),)
value :  [ 10  40 500 500  70  72]
