In [69]:
import numpy as np
#converting 2D arry to 1D array
a=np.array ([[65,80,29],[30,80,10],[99,32,28]])
print(a)

[[65 80 29]
 [30 80 10]
 [99 32 28]]


In [10]:
#converting 2D arry to 1D array
#a.ravel()
#or
#a.flatten()
#or
a.reshape(-1)

array([65, 80, 29, 30, 80, 10, 99, 32, 28])

In [12]:
#create 1D array
a=np.arange(10,81,10) #start=10 stop=81-1=80 step=10
print (a)

[10 20 30 40 50 60 70 80]


In [14]:
#converting 1D arry to 2D array
a.reshape(4,2)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [15]:
#converting 1D arry to 2D array
a.reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [16]:
#sorrt() in2D array;- to record in assanding order only
#create 2D matrix
a=np.array([[65,50,80],[50,43,42],[49,90,52]])
print(a)

[[65 50 80]
 [50 43 42]
 [49 90 52]]


In [17]:
#sort()\
a.sort() #by default takes axis=1 meaning horizontally meanig left to  right

In [18]:
a #sorted output

array([[50, 65, 80],
       [42, 43, 50],
       [49, 52, 90]])

In [19]:
a.sort(axis=0) #vertical  sorting meaning top to bottom

In [20]:
a# sorted output

array([[42, 43, 50],
       [49, 52, 80],
       [50, 65, 90]])

In [23]:
#arithmetic opperation on 2 or more 2D array
#i.e sum, sub, multiply, divide of 2 matrix
#creating 2 2D matrix a and b
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("a matrix =")
print(a)
print("b matrix =")
print(b)

a matrix =
[[1 2]
 [3 4]]
b matrix =
[[5 6]
 [7 8]]


In [24]:
#sum of matrix
a+b

array([[ 6,  8],
       [10, 12]])

In [25]:
#subtraction of matrix
a-b

array([[-4, -4],
       [-4, -4]])

In [26]:
#multiplication
#1. cross multiplication
#2. dot multiplication

#cross
a*b

array([[ 5, 12],
       [21, 32]])

In [27]:
#dot 
a.dot(b)

array([[19, 22],
       [43, 50]])

In [29]:
#special type of 2D array
#1. zeros() 2.ones() 3.empty() 4.identify() or eye()


In [39]:
#zeros()
z=np.zeros((3,4)) #values pass in tuple (rosize,colsize)
#bydefault type=float
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
z[1,1]=45 #replacing element to ne value
print(z)

[[ 0.  0.  0.  0.]
 [ 0. 45.  0.  0.]
 [ 0.  0.  0.  0.]]


In [41]:
z.fill(8)
print(z)

[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]


array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [46]:
z=np.zeros((3,3),int)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [47]:
o=np.ones((4,4),int)
print(o)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [52]:
e=np.empty((4,4))
print(e)

[[4.67296746e-307 1.69121096e-306 1.29061074e-306 8.34441742e-308]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 1.15706896e-306 1.33512173e-306 1.42404727e-306]]


In [53]:
e=np.empty((4,4),int)
print(e)

[[   0    0    0    0]
 [   0    0    0    0]
 [   0    0 1180    0]
 [   0    0    0    0]]


In [55]:
#creating identity matrix ; always square  row and col ill remain same
i=np.identity(2) #here 2 means no of ro and col=2
print(i)

[[1. 0.]
 [0. 1.]]


In [56]:
#creating identity matrix ; always square  row and col ill remain same
i=np.identity(4) #here 5 means no of row and col=4
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [61]:
#creating identity matrix ; always square  row and col ill remain same
i=np.eye(2) #here 2 means no of ro and col=2
print(i)

[[1. 0.]
 [0. 1.]]


In [63]:
#creating identity matrix ; always square  row and col ill remain same
i=np.identity(2,int) #here 2 means no of ro and col=2 for int
print(i)

[[1 0]
 [0 1]]


In [64]:
#creating identity matrix ; always square  row and col ill remain same
i=np.eye(2,int)
print(i)

TypeError: 'type' object cannot be interpreted as an integer

In [65]:
#creating identity matrix ; always square  row and col ill remain same
i=np.eye(2,dtype=int) 
print(i)

[[1 0]
 [0 1]]


In [66]:
a=np.array([[2,5],[12,7]])
print (a)

[[ 2  5]
 [12  7]]


In [67]:
#transpose
a.T

array([[ 2, 12],
       [ 5,  7]])

In [71]:
#concatenate means to  join 2 or more matrix (2D array)
a=np.array([[50,60],[80,90]])
b=np.array([[85,92,56],[53,78,55]])
print("a matrix =")
print(a)
print("b matrix =")
print(b)

a matrix =
[[50 60]
 [80 90]]
b matrix =
[[85 92 56]
 [53 78 55]]


In [73]:
#to join means to concate 2 matrix a and b and hold in new matrix c
c=np.concatenate((a,b),axis=1)#bydefault axis=0
print(c)

[[50 60 85 92 56]
 [80 90 53 78 55]]


In [77]:
a=np.array([[60,75],[53,79]])
b=np.array([[50,60],[70,80],[90,20],[50,55]])
print("a matrix =")
print(a)
print("b matrix =")
print(b)

a matrix =
[[60 75]
 [53 79]]
b matrix =
[[50 60]
 [70 80]
 [90 20]
 [50 55]]


In [80]:
#concatenating vertically
c=np.concatenate((a,b),axis=0)
print(c)

[[60 75]
 [53 79]
 [50 60]
 [70 80]
 [90 20]
 [50 55]]


In [83]:
#conditional filter
#accessing odd data
c[c%2!=0] #c[condition]

array([75, 53, 79, 55])

In [85]:
#conditional filter
#accessing odd data and filling it with -1
#replacing  all odd no =-1
c[c%2!=0]=-1 #c[condition]
print(c)

[[60 -1]
 [-1 -1]
 [50 60]
 [70 80]
 [90 20]
 [50 -1]]


In [88]:
#brodcasting
5*c #where 5 is a scaler vector

array([[300,  -5],
       [ -5,  -5],
       [250, 300],
       [350, 400],
       [450, 100],
       [250,  -5]])

In [89]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("a matrix =")
print(a)

a matrix =
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [90]:
b=np.array([[1,2,3]])
print(b)

[[1 2 3]]


In [91]:
a*b

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])