In [1]:
#K-NN : K nearest Neighbours method : It is classification algorithm
#it is also supervised learning algorithm
#use dataset user_data.csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#To load dataset
df=pd.read_csv("user_data.csv")
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
df["Purchased"].unique()

array([0, 1], dtype=int64)

In [4]:
#To remove unwanted features User ID and Gender 
df.drop(["User ID","Gender"],axis=1,inplace=True)

In [5]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [6]:
#check null values
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [7]:
#check datatypes
df.dtypes

Age                int64
EstimatedSalary    int64
Purchased          int64
dtype: object

In [8]:
#select input and output 
X=df.drop("Purchased",axis=1)
Y=df["Purchased"]

In [9]:
#train_test_split
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.3,random_state=1)

In [10]:
#apply scaling on X_train and X_test
from sklearn.preprocessing import StandardScaler
#Create the object of StandardScaler class
ss=StandardScaler()
Xtrain=ss.fit_transform(Xtrain)
Xtest=ss.transform(Xtest)

In [11]:
#creating model
def create_model(model):
    model.fit(Xtrain,Ytrain)
    Ypred=model.predict(Xtest)
    print("Classification report\n",classification_report(Ytest,Ypred))
    print("Confusion Matrix\n",confusion_matrix(Ytest,Ypred))
    return model

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [13]:
#creating basline model
from sklearn.linear_model import LogisticRegression

In [14]:
#creating Object
lr=LogisticRegression()

In [15]:
#calling function
lr=create_model(lr)

Classification report
               precision    recall  f1-score   support

           0       0.82      0.90      0.86        72
           1       0.83      0.71      0.76        48

    accuracy                           0.82       120
   macro avg       0.83      0.81      0.81       120
weighted avg       0.83      0.82      0.82       120

Confusion Matrix
 [[65  7]
 [14 34]]


In [16]:
#check data unbalance or not
df["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [17]:
#decission tree

In [18]:
#pruning

In [19]:
#random forest

In [20]:
#ADA boost

# Applying KNN

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
#creating object
knc=KNeighborsClassifier(n_neighbors=5, metric='minkowski',p=2)
#p=2 means Euclidean metric means sqrt(x2-x1)*2+(y2-y1)*2

In [23]:
#calling function
knc=create_model(knc)

Classification report
               precision    recall  f1-score   support

           0       0.94      0.85      0.89        72
           1       0.80      0.92      0.85        48

    accuracy                           0.88       120
   macro avg       0.87      0.88      0.87       120
weighted avg       0.88      0.88      0.88       120

Confusion Matrix
 [[61 11]
 [ 4 44]]
