In [1]:
#Dataset use telecomm_churn : - 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#to load the dataset
df=pd.read_csv("telecom_churn.csv")
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
#to show how many rows and column
df.shape

(7043, 21)

In [4]:
#to check null values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
#to check datatype
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [6]:
#to check all unique values in TotalCharges
df["TotalCharges"].value_counts()

          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: TotalCharges, Length: 6531, dtype: int64

In [7]:
df["TotalCharges"].replace(" ",np.nan,inplace=True)

In [8]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [9]:
#changing datatype of TotalCharges
df["TotalCharges"]=df["TotalCharges"].astype("float")
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [10]:
#finding mean of TotalCharges
m=df["TotalCharges"].mean()
m

2283.3004408418656

In [11]:
#filling null value with mean of Totalcharges
df["TotalCharges"].fillna(m,inplace=True)
#check again null values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [12]:
#removing unwanted column
df.drop("customerID",axis=1,inplace=True)

In [13]:
#seprating object type data from numeric data
df_cat=df.select_dtypes("object")
#seperating numeric data 
df_num=df.select_dtypes(["float64","int64"])

In [14]:
#to convert object type data into numeric type data using LabelEncoder
from sklearn.preprocessing import LabelEncoder
for col in df_cat:
    #creating object of labeln Encoder
    le=LabelEncoder()
    df_cat[col]=le.fit_transform(df_cat[col])

In [15]:
#checking df_cat
df_cat.head()

gender  Partner  Dependents  PhoneService  MultipleLines  InternetService  \
0       0        1           0             0              1                0   
1       1        0           0             1              0                0   
2       1        0           0             1              0                0   
3       1        0           0             0              1                0   
4       0        0           0             1              0                1   

   OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
0               0             2                 0            0            0   
1               2             0                 2            0            0   
2               2             2                 0            0            0   
3               2             0                 2            2            0   
4               0             0                 0            0            0   

   StreamingMovies  Contract  PaperlessBilling  PaymentMethod  Churn  
0                0         0                 1              2      0  
1                0         1                 0              3      0  
2                0         0                 1              3      1  
3                0         1                 0              0      0  
4                0         0                 1              2      1

In [16]:
#concatnating Df_cat and df_num
df_new=pd.concat([df_num,df_cat],axis=1)
df_new.head()

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender  Partner  \
0              0       1           29.85         29.85       0        1   
1              0      34           56.95       1889.50       1        0   
2              0       2           53.85        108.15       1        0   
3              0      45           42.30       1840.75       1        0   
4              0       2           70.70        151.65       0        0   

   Dependents  PhoneService  MultipleLines  InternetService  OnlineSecurity  \
0           0             0              1                0               0   
1           0             1              0                0               2   
2           0             1              0                0               2   
3           0             0              1                0               2   
4           0             1              0                1               0   

   OnlineBackup  DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0             2                 0            0            0                0   
1             0                 2            0            0                0   
2             2                 0            0            0                0   
3             0                 2            2            0                0   
4             0                 0            0            0                0   

   Contract  PaperlessBilling  PaymentMethod  Churn  
0         0                 1              2      0  
1         1                 0              3      0  
2         0                 1              3      1  
3         1                 0              0      0  
4         0                 1              2      1

In [17]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   SeniorCitizen     7043 non-null   int64  
 1   tenure            7043 non-null   int64  
 2   MonthlyCharges    7043 non-null   float64
 3   TotalCharges      7043 non-null   float64
 4   gender            7043 non-null   int32  
 5   Partner           7043 non-null   int32  
 6   Dependents        7043 non-null   int32  
 7   PhoneService      7043 non-null   int32  
 8   MultipleLines     7043 non-null   int32  
 9   InternetService   7043 non-null   int32  
 10  OnlineSecurity    7043 non-null   int32  
 11  OnlineBackup      7043 non-null   int32  
 12  DeviceProtection  7043 non-null   int32  
 13  TechSupport       7043 non-null   int32  
 14  StreamingTV       7043 non-null   int32  
 15  StreamingMovies   7043 non-null   int32  
 16  Contract          7043 non-null   int32  


In [18]:
#Selecting Input And Output
X=df_new.drop("Churn",axis=1)#input
Y=df_new["Churn"] #output

In [19]:
X.head()

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender  Partner  \
0              0       1           29.85         29.85       0        1   
1              0      34           56.95       1889.50       1        0   
2              0       2           53.85        108.15       1        0   
3              0      45           42.30       1840.75       1        0   
4              0       2           70.70        151.65       0        0   

   Dependents  PhoneService  MultipleLines  InternetService  OnlineSecurity  \
0           0             0              1                0               0   
1           0             1              0                0               2   
2           0             1              0                0               2   
3           0             0              1                0               2   
4           0             1              0                1               0   

   OnlineBackup  DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0             2                 0            0            0                0   
1             0                 2            0            0                0   
2             2                 0            0            0                0   
3             0                 2            2            0                0   
4             0                 0            0            0                0   

   Contract  PaperlessBilling  PaymentMethod  
0         0                 1              2  
1         1                 0              3  
2         0                 1              3  
3         1                 0              0  
4         0                 1              2

In [20]:
#taking ratio of 70 and 30 to train test and split 
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.3,random_state=1)

In [21]:
#1. Standardization
from sklearn.preprocessing import StandardScaler

#fit_transform on training data Xtrain and 
#transform on testing_data means Xtest :
#create object of StandardScaler class
ss=StandardScaler()
Xtrain=ss.fit_transform(Xtrain)
Xtest=ss.transform(Xtest)

In [22]:
#dataset is a classification dataset, Hence we need to predict weather the customer will churn or not
#first Baseline Model:
#creating a function
def create_model(model): #model is user defined parameter as a object
    model.fit(Xtrain,Ytrain) #training the model
    Ypred=model.predict(Xtest) # testing the model
    print("Classification_Report\n" ,classification_report(Ytest,Ypred))
    print("Confusion_Matrix\n",confusion_matrix(Ytest,Ypred))
    return model

In [23]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [24]:
#Base Line Model means use Logistic Regression(we predict yes/no values then 
#use classification algorithm)
from sklearn.linear_model import LogisticRegression

In [25]:
#creating object of LogisticRegression
lr=LogisticRegression()

In [26]:
#Calling Function
lr=create_model(lr)

Classification_Report
               precision    recall  f1-score   support

           0       0.86      0.88      0.87      1585
           1       0.63      0.59      0.61       528

    accuracy                           0.81      2113
   macro avg       0.75      0.73      0.74      2113
weighted avg       0.81      0.81      0.81      2113

Confusion_Matrix
 [[1401  184]
 [ 219  309]]


In [27]:
df["Churn"].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [28]:
#if data is imbalance then use sampling Technique
#We handle Imbalance data ,We take some Samling Technique.
''' There are 2 types of Sampling Technique : -
1. Random Over Sampling TEchnique  2.Random Under Sampling TEchnique'''

' There are 2 types of Sampling Technique : -\n1. Random Over Sampling TEchnique  2.Random Under Sampling TEchnique'

In [29]:
#If you have basically reducing the majority class means 
#remove record randomly from majority class that is known as 
#Random Undersampling ,
#and if you are increasing the minority class means create a duplicate
#row randomly that is known as Random over sampling

In [30]:
#install package imblearn
#!pip install imblearn

In [31]:
#using random over sample
from imblearn.over_sampling import RandomOverSampler

In [32]:
#creating object
#RandomOversampler
#create object of  RandomOverSampler() class
ros=RandomOverSampler(random_state=1)

In [33]:
Xtrain_ros,Ytrain_ros=ros.fit_resample(Xtrain,Ytrain)
#fit_resample() inbuilt method of RandomOverSampler class

In [34]:
pd.Series(Ytrain).value_counts() #check whem not balanced

0    3589
1    1341
Name: Churn, dtype: int64

In [35]:
pd.Series(Ytrain_ros).value_counts() #after balancing

0    3589
1    3589
Name: Churn, dtype: int64

In [36]:
#applying over sample on testing Data
Xtest_ros,Ytest_ros=ros.fit_resample(Xtest,Ytest)

In [37]:
pd.Series(Ytest).value_counts() #before Over sampling 

0    1585
1     528
Name: Churn, dtype: int64

In [38]:
pd.Series(Ytest_ros).value_counts() #after Over sampling

0    1585
1    1585
Name: Churn, dtype: int64

In [39]:
def create_model1(model): #model is user defined parameter as a object
    model.fit(Xtrain_ros,Ytrain_ros) #training the model
    Ypred=model.predict(Xtest_ros) # testing the model
    print("Classification_Report\n" ,classification_report(Ytest_ros,Ypred))
    print("Confusion_Matrix\n",confusion_matrix(Ytest_ros,Ypred))
    return model

In [40]:
#baseline model LogisticRegression
#creating object
lr=LogisticRegression()

In [41]:
#calling Function
lr=create_model1(lr)

Classification_Report
               precision    recall  f1-score   support

           0       0.80      0.73      0.77      1585
           1       0.75      0.82      0.79      1585

    accuracy                           0.78      3170
   macro avg       0.78      0.78      0.78      3170
weighted avg       0.78      0.78      0.78      3170

Confusion_Matrix
 [[1162  423]
 [ 284 1301]]


In [42]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
#creating Object of DecisionTreeClassifeir
dt=DecisionTreeClassifier()

In [44]:
#calling Function
dt=create_model1(dt)

Classification_Report
               precision    recall  f1-score   support

           0       0.64      0.82      0.72      1585
           1       0.75      0.54      0.63      1585

    accuracy                           0.68      3170
   macro avg       0.69      0.68      0.67      3170
weighted avg       0.69      0.68      0.67      3170

Confusion_Matrix
 [[1302  283]
 [ 735  850]]


In [45]:
IG=dt.feature_importances_
IG

array([0.01981846, 0.10433757, 0.2083337 , 0.18065465, 0.01809216,
       0.02122821, 0.01640444, 0.00109512, 0.01238447, 0.00878082,
       0.04339398, 0.01793946, 0.01400124, 0.01536741, 0.01005055,
       0.01309709, 0.22989124, 0.01860541, 0.04652402])

In [46]:
dic={"Columns":X.columns,"IG":IG}
df_Ig=pd.DataFrame(dic)
df_Ig.sort_values("IG",ascending=False)

Columns        IG
16          Contract  0.229891
2     MonthlyCharges  0.208334
3       TotalCharges  0.180655
1             tenure  0.104338
18     PaymentMethod  0.046524
10    OnlineSecurity  0.043394
5            Partner  0.021228
0      SeniorCitizen  0.019818
17  PaperlessBilling  0.018605
4             gender  0.018092
11      OnlineBackup  0.017939
6         Dependents  0.016404
13       TechSupport  0.015367
12  DeviceProtection  0.014001
15   StreamingMovies  0.013097
8      MultipleLines  0.012384
14       StreamingTV  0.010051
9    InternetService  0.008781
7       PhoneService  0.001095

In [47]:
#creat A tree

In [48]:
#applying Pruning technique
#max_depth=8
dt1=DecisionTreeClassifier(max_depth=5,random_state=1)


In [49]:
#call function
dt1=create_model1(dt1)

Classification_Report
               precision    recall  f1-score   support

           0       0.77      0.72      0.74      1585
           1       0.74      0.79      0.76      1585

    accuracy                           0.75      3170
   macro avg       0.75      0.75      0.75      3170
weighted avg       0.75      0.75      0.75      3170

Confusion_Matrix
 [[1138  447]
 [ 340 1245]]
