In [1]:
#support Vector Machine on Bank DataSet
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#load dataset
df=pd.read_csv("bank.csv")
df.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [3]:
#check data balanced or not
df["deposit"].value_counts()

0    5873
1    5289
Name: deposit, dtype: int64

In [25]:
df.shape

(11162, 17)

In [4]:
#check null value
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [5]:
#datatype
df.dtypes

age          int64
job          int64
marital      int64
education    int64
default      int64
balance      int64
housing      int64
loan         int64
contact      int64
day          int64
month        int64
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome     int64
deposit      int64
dtype: object

In [6]:
X=df.drop("deposit",axis=1)#input
Y=df["deposit"]#output

In [7]:
#train_test_split seperating 70% training and 30% testing Data
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.3,random_state=1)

In [8]:
#scaling
from sklearn.preprocessing import StandardScaler

In [9]:
#creating object and apply scaling
ss=StandardScaler()
Xtrain=ss.fit_transform(Xtrain)
Xtest=ss.transform(Xtest)

In [10]:
#creating function
def create_model(model):
    model.fit(Xtrain,Ytrain)
    Ypred=model.predict(Xtest)
    print("Classification Report\n",classification_report(Ytest,Ypred))
    print("Confusion Matrix\n",confusion_matrix(Ytest,Ypred))
    return model

In [11]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [12]:
#applying Base line Model
#decision Tree
#pruning Technique
#all boosting Technique
#random Forest

# Applying Support Vector Machine

In [13]:
#Apply Support vector  machine : -
#use SVM : support vector machine : - classification algorithm
#There are 3 types of SVM (Kernel function) : -
#1. Linear kernel function of SVM : means suppose data are linearly 
#separatable with the help of straight line  ,it is known as decision boundary
#or hyperplane
#call class LinearSVC inbuilt class
#SVC : support vector classifier
'''Call Function '''
from sklearn.svm import LinearSVC

In [14]:
#creating object of Linear SVC Class
svc=LinearSVC(random_state=1) #hard Margin bydefault because error is not yet added

In [15]:
svc=create_model(svc)

Classification Report
               precision    recall  f1-score   support

           0       0.80      0.82      0.81      1760
           1       0.79      0.77      0.78      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.80      0.80      0.80      3349

Confusion Matrix
 [[1444  316]
 [ 364 1225]]


### here recall is 0.77 which is good but we can more better
1. means can be possible ,model is overfit  why  perhaps , can be no error on training time but error on testing time , 
2. what  do we do?
   add some external error on training time  if create a object of LinearSVC class

In [16]:
#Soft margin means to reduced overfitting situation means some error add on
#training time 
#create object of LinearSVC class
svc1=LinearSVC(random_state=1,C=0.5)
##add some error on training time set error 0.01,0.05,....... 
#value of parameter C is not more than 1

In [17]:
#calling function
svc1=create_model(svc1)

Classification Report
               precision    recall  f1-score   support

           0       0.80      0.82      0.81      1760
           1       0.79      0.77      0.78      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.80      0.80      0.80      3349

Confusion Matrix
 [[1444  316]
 [ 364 1225]]


## Here we can see that even after adding error we do not have any changes in the score of the model
hence the model is not overfit 
which means the model is not working with linear SVC

In [18]:
#if add external error on training time but no any changes on score
#means given dataset in non-Linear
#can be possible , dataset is not linear means dataset is non-linear  .
#use Non-linear kernal function of SVM means 2 classes are not 
#separatable with straight line

In [19]:
#There are 3 types of Kernal function of SVM
#1. Linear SVC  : use for linear data
#2. Non-Linear SVC : use for non-linear data
#1. polynomial kernal function : increase the low dimension to high dimension
#2. radial basis kernal function

#here 2. polynomial kernal function : increase the low dimension to 
#high dimension
#3. radial basis kernal function  both are non-linear data

## 2. Polynomal Kernal Function (Non-Linear)

In [20]:
#calling function
from sklearn.svm import SVC
#svc inbuilt class for non- linear data

In [21]:
#creating Object
poly_svc=SVC(random_state=1,kernel="poly")

In [22]:
#calling Function
poly_svc=create_model(poly_svc)

Classification Report
               precision    recall  f1-score   support

           0       0.82      0.81      0.81      1760
           1       0.79      0.80      0.80      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.81      0.80      0.80      3349

Confusion Matrix
 [[1417  343]
 [ 311 1278]]


In [23]:
#we try using second kernel function that is radial base function\
#creating object of svc for radial function now
radial_svc=SVC(random_state=1,kernel="rbf")

In [24]:
#calling function
radial_svc=create_model(radial_svc)

Classification Report
               precision    recall  f1-score   support

           0       0.84      0.80      0.82      1760
           1       0.79      0.84      0.81      1589

    accuracy                           0.82      3349
   macro avg       0.82      0.82      0.82      3349
weighted avg       0.82      0.82      0.82      3349

Confusion Matrix
 [[1407  353]
 [ 262 1327]]
